
# Introduction

Programming in Rust is totally different from coding in C or C++ - and of cause also very different from coding in R or Python. I will talk about typed variables later on, but want to first highlight the security features Rust implements.

In Rust a variable is 'owned' by a function - possibly comparable to R. But instead of R which simply copies the data into every function in Rust the variables can not be changed inside of the function. It is especially prohibited to e.g. give a function a file object to write to. Only the function that did create the file object can write to it.

This is also true for e.g a HashMap that stores objects (some data) in combination with e.g. a string key. If you want to modify the stored object you need the class that 'owns' this object make the changes. I have not hidden any of these problems inside this tutorial. That is something you need to learn the hard way.

# Variables

Rust uses strong typed variables. This does mean that you need to define your variables as a specific type.
As an example you can store integer values as u8, u16, u32, u64, u128, i8, i16, i32, i64, i128, usize or integer.
All of these types can not be compared against each other. So if you want to create some data structures it does help to choose the same type for all data (eg. u64). 
The difference between the integer types are the range of values they can contain: u8 and i8 are 8 bit long whereas u128 and i128 are 128 bit long; the u types are unsigned and can not contain negative values. 
Usize is the default integer type and is dependent on your computer type. On 64 bit computers it is the same as a u64 - but you still can not compare it directly to u64.

## Target Audience

This tutorial does not explain to you how to program. I assume you are absolutely able to do that.
In addition there a re tons of other tutorials that explain that to you.

What I found most important for my work is to try to understand code I have not written and hunt bugs I am not responsible for. In addition I assume you all benefit the most of a larger set of code snippets you can go back to and copy code from. Code you can double check how something could work.

# Examples

Here I will show you the minimal Rust programming:

- define a variable
- do a small calculation

### Integers

Using RStudio at the moment I can show you how you define a variable in Rust:

```{extendr, eval=eval_rextender}
let x = 5;
let y = 7;
let z = x*y;

rprintln!("{x} * {y} = {z}");
```

The print statement here is not Rust but specific for the R extension rextendr.
The Rust equivalent to the rprintln!() is println!().
Please ignore my usage of rprintln! - it is an artifact from me using Rstudio to compile this tutorial.

The interesting part here is how you define variables: "let \<varname\>:\<type\> = \<value\>;"

Why did we not define the type of integer we want to store?

Here Rust silently assumes you want to use the default integer type usize.
If you want to specify the integer type you want to use here you could write the following:

```{extendr, eval=eval_rextender}
let x:u8 = 5;
let y:u8 = 7;
let z = x*y;

rprintln!("{x} * {y} = {z}");
```

OK - this works in RStudio - what about breaking this code?


# Create a new Rust program 

Rust is a compiled language and therefore interacting with it using a jupyter notebook or Rmd file does limit the language a lot.
Hence it makes more sense to compile Rust programs and use them on the command line. 

As an example of why - I deliberately broke the integer example:

```
let x:u8 = 5;
let y:u16 = 7;
let z = x*y;

rprintln!("{x} * {y} = {z}");
```

Compiling this in RStudio breaks the html generation and I can not show the error here using this code. But if I create a stand alone 'program' of it it works:

```{r , include = FALSE, eval=FALSE}
unlink( 'workshop', recursive=TRUE )
```

And then create an empty class structure:

```{bash, eval=FALSE}
cargo new workshop --bin
```

Open the created file "workshop/srv/main.rs" and replace the "println!("Hello, world!");" with the broken code we had before.

Compile the new program:

```{bash,  error=TRUE}
cd workshop
cargo build -r 2>&1 | sed -r "s/\x1B\[[0-9;]*[mGKH]//g"
```

Here you see the output from the Rust compiler. Do you see the beauty of this?
The compiler explains the error. The most reasonable fix here would of cause be to not define the y as u16 in the first place - right?

This becomes even more beautiful if you want to know more about the error: you can simple ask Rust to explain more:

```{bash, error=TRUE}
rustc --explain E0308
```


# More complicated error hunting:

The bugs so far were not very complicated - right? Now we need to dig deeper and I recommend you to use your programming IDE of choice to look into a new broken program. Rstudio could possibly also do.

Lets look in the simple_problem folder in [this github repo](https://github.com/stela2502/Rust_Programming_1).

Download (clone) the repo using git ``git clone https://github.com/stela2502/Rust_Programming_1``. Open the folder 'simple_error' in your IDE and open a terminal and cd into this folder.

There you run:
```{bash,  error=TRUE}
cd simple_error
cargo build -r  2>&1 | sed -r "s/\x1B\[[0-9;]*[mGKH]//g"
```

It is almost no fun hiding programming errors as the compiler will already tell you what to do - right?
I think this nevertheless will be fun...


## Problem 1

Each line needs to end with a ';'. All but the last line in a function if you want to return a value.

## Promblem 2

We do not have a 'data' variable in the sum function. Here the data is called 'v' - fix that.

Now the code compiles:
```{bash,  error=TRUE}
cd simple_fixed
cargo build -r 2>&1 | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"
target/release/simple_error
```

Does the output make sense?

## Problem 3

No it is wrong: We need to switch the variables in the println! call.

## Problem 4

Wait - we tried to sum up the values 6, 7, 8 and 9 - that is not 10!
How do you fix that?

This one is rather complicated and I recommend you to add a test case before you try to fix it.


# Tests in Rust

Problem 4 is a good example for a really annoying bug. To get them and also make sure you will not re-introduce this bug later it makes a lot of sense to write a test that detects the error you have in your code before you try to fix it:


Rust has a nice way to do so:
Add this to the script

```
#[cfg(test)]
mod tests {
    use crate::sum;
    #[test]
    fn check_sum() {
      
      let data:Vec<usize> = vec![1,2,3,4,5,6,7,8,9];
      let ids:Vec<usize> = vec![5,6,7,8];
      
    	assert_eq!( sum( &data, &ids ), 30 );
    }
}
```

And now you can test your script by 

```{bash,  error=TRUE}
cd simple_fixed
cargo test -r 2>&1 | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"
```

I hope you can find and fix the bug.

# A short break


