# How do you get data into Rust?

Getting data into a compiled langue has always been a problem for me.
Hence I'll tell you how I finally managed to get data into Rust - just copy paste the solution - I do the same.

The git repo contains a folder 'read_data' which is a simple Rust package.
Looking into it you see a Cargo.toml. This file describes your package and is comparable to the R DESCRIPTION file.
Here you define the package and the dependencies. Just look into the example. It should be self explanatory.

The src folder contains the code files with main.rs defining the executable and the lib.rs defining the library part of the package.
The additional data.rs file contains the code for the library in this package and needs to be mentioned in the lib.rs file to be compiled.


Let's dig through the code.


### Start with the main.rs file. 

This file will be compiled to be the executable. The program starts with the main function.

- lines 0..7   import the used classes
- lines 13..22 define the command line options
- lines 24..55 define the main function

In the main function most of the code is a timer functionality that I do think is extremely useful.

```
let now = SystemTime::now();

// do the stuff

match now.elapsed() {
    Ok(elapsed) => {
        let mut milli = elapsed.as_millis();
        
        let mil = milli % 1000;
        milli= (milli - mil) /1000;

        let sec = milli % 60;
        milli= (milli -sec) /60;

        let min = milli % 60;
        milli= (milli -min) /60;

        println!("finished in {milli} h {min} min {sec} sec {mil} milli sec");
    },
    Err(e) => {println!("Error: {e:?}");}
}
```

Using 'let \<var_name\>: \<type\> = \<value\>' defines variables in Rust.
The type does not need to be included in the definition if the compiler can identify the type itself.


The 'match' part is the main Rust error handling functionality. It is comparable to the C switch statement as it allows to match a value against multiple patterns and execute code based on the first matching pattern. 

The function 'now.elapsed()' can fail and therefore returns a "Result\<Duration, SystemTimeError\>" instead of only a Duration.
This allows for the match to check if an error has occurred using the two functions Ok and Err that both take a Result as input:

```
match <statement> {
    Ok(<varname>) => { <do something with the variable> },
    Err(e) => { <do something with the error> },
};
```

I am sure you will like this ;-)


**The reading of the command line options:** 

```
let opts: Opts = Opts::parse();
let mut sep = '\t';
if &opts.sep != "\\t"{
    println!("I set sep to {}", opts.sep );
    sep = opts.sep.chars().next().unwrap(); 
}
```

The first line parses the command line. The rest is my way to handle the problem that you can not give Rust a '\\t' on the command line as the used char class can only contain one literal.
So I have used the tab as default instead of dealing with this problem in any other way.

**The reading and printing of the data table**

```
let data = Data::read_file( &opts.data , sep );
data.print();
```

Quite a lot of overhead to just read a tab separated file into a script - or?
But you have not even seen most of it as what you see here first defines a data variable using the Data::read_file() function and then uses the Data::print() function to print the contents of the data object. Therefore the real code loading the data is hidden in the library.

### The lib.rs file

```
pub mod data;
```

Oh that is boring. It only imports the code from data.rs ...

### The data.rs file

This file now defines the Data class.

- lines 0..5 define the dependencies
- lines 8..14 define the data part of the class
- lines 17..110 code the functions
- lines 112..126 implement the tests for this class

A class in Rust is defined by creating the data structure for the class (struct Data {}) and then implementing functions for the class (impl Data {}).
Functions can be defined with 

```
<accessability> fn <function name> (<variables>) -> <return value> { 
	<code> 
} 
```

Lets look into the new function:

```
pub fn new( rows:usize, cols:usize, data: Vec::<f64>, rownames: Vec::<String> ) -> Self {

	let ret = Array::from_iter(&mut data.into_iter());
	let data = ret.into_shape([rows, cols]).unwrap();

	Self {
		rows, 
		cols,
		rownames,
		data,
	}
}
```

First this function can be called from outside the class - it is public. And this is what it does: it takes ownership of the data using the into_iter() function. This means that we can no longer access data in the main function. This is part of Rusts more secure memory management: Only one function can have access to the data. We then create an Array object from this data (from_iter) and finally we re-format the data into a two dimensional table (into_shape). The ending unwrap() call handles any possible error for the reshape process. 

The Self{} statement at the end creates the object from it's parts. Here we have the rows, cols, the rownames (from the function call) and the data array. This line is not ending with a ';'. Here the compiler instead returns the Self object. 

This is quite simple - or?

### The read_file function

The read_file function shows a general problem of compiled languages.
Normally you should know how much data you want to store in the objects as the memory needs to be requested per variable.
Adding more 'space' to a variable is quite costly. Hence here we iterate over the data twice. Lines 32..52 read the data and 'only' collect the column and row counts.

The 'line' object contains one line of the data file and the reader.lines() function returns a 'Result' - meaning it is normal that this function might not work.
And - again - this is the common way to treat a Result in Rust:

```
let mut header =true;
for line in reader.lines() {
    if header{
        // just drop the header
        header = false;
        continue;
    }
    match line {
        Ok(line) => {
            header =true;
            for mut val in line.split( sep ).collect::<Vec<&str>>(){ ## here is the mut!
                if header{
                    names.push( val.to_string() );
                    header = false;
                }else {
                    val = val.trim();
                    let v = match val.parse::<f64>() {
                        Ok( v ) => v,
                        Err(_err) => {
                            match val.parse::<usize>(){
                                Ok(v) =>  { 
                                    v as f64
                                },
                                Err(err) => {
                                    eprintln!("I could not parse '{val}' to usize or f64 {err:?}");
                                    0.0
                                },
                            }
                        },
                    };
                    arr.push( v );
                }
            }
        },
        Err(err) => {
            panic!("Unexpected error reading the csv file: {err:?}");
        }
    }
}
```

What does this 'mut' mean? Rust differentiates between variables you only store a value in once and variables that you can modify.
So whenever you want to assign a value to a variable more than once you need to declare the variable as mut.

```
for mut val in line.split( sep ).collect::<Vec<&str>>()
```

Translates to: split the line by 'sep' and give me ownership of the variables you create as Vec\<&str\>; iterate over the variables in the vector and I want to be able to modify them!

Where do we modify the value? ``val = val.trim();`` does remove whitespace from the strings. This is necessary as " 2" can not be parsed as 2:\<usize\>. Tried that and it broke ;-)
Rust also does not want to parse an int as float and vice versa. So therefore I need to differentiate between the two options here, too. 
The only other interesting part here is the ``let v = match val.parse::<f64>() {``. This tries to convert the data into a f64 and if that fails it converts it to a usize. And if both ties fail it throws an error, but does not break - so more like a warning. In this case it returns 0.0 (a f64).


### And now try the tool:


```{bash,  error=TRUE}
cd read_data
cargo build -r
target/release/read_data -h
```

And we can even run the test with some data file:

```{bash,  error=TRUE}
cd read_data
target/release/read_data -d testData/Spellman_Yeast_Cell_Cycle.tsv
```