# Outlook

A short to very short outlook, describing how nucleotide sequences can be handled in Rust.
This is not meant to be understood right now, but I wanted to give you an impression of what Rust can do with DNA sequences:

Sequences can also be compacted using two bit per nucleotide and then a single u64 can contain the same info as a 32bp String.
With being an integer this representation of a DNA sequence opens up possibilities that you do simply not have in R.

```{extendr, eval=eval_rextender}
// logics copied from https://github.com/COMBINE-lab/kmers/
pub type Base = u8;
pub const A: Base = 0;
pub const C: Base = 1;
pub const G: Base = 2;
pub const T: Base = 3;

pub fn encode_binary(c: char) -> Base {
    // might have to play some tricks for lookup in a const
    // array at some point
    match c {
        'A' | 'a' => A,
        'C' | 'c' => C,
        'G' | 'g' => G,
        'T' | 't' => T,
        _ => panic!("cannot decode {c} into 2 bit encoding"),
    }
}

let s = String::from("AGCTACGT");
rprintln!("How Rust can look at the sequence {s}");
let t = s.as_bytes();
rprintln!("as_bytes {t:?}");
let st = std::str::from_utf8(t).unwrap();
rprintln!("as str {st:?}");

let mut w = 0_u8;
for c in st.chars().rev() {
  w <<= 2;
  w |= encode_binary(c);
}
rprintln!("and as single u8 integer {w}");
rprintln!("which looks like this in binary form: {w:b}");

let faster =std::str::from_utf8( b"AGCTAGCT").unwrap();

for c in faster.chars().rev() {
  w <<= 2;
  w |= encode_binary(c);
}
rprintln!("and now in one line from string to binary: {w:b}");
```


What does this do? 
In the beginning it defined a Base variable of class type. This variable is later used to define which kind of data you can process using this logic (e.g. 8, 16, 32 or even 64 bp of sequence info). The next four lines define which sequences should be converted into which 'number'.
It helps tremendously if you try to think of 0-3 as binary numbers: #00, #01, #10 and #11.

Defining something using const instead of let can help make the code more reliable, efficient, and maintainable by enforcing immutability and compile-time evaluation, and by providing global scope and better type checking. For me this translates in - just do it this way - it does certainly not hurt.

The 'let part' of the script defines the string we want to convert, converts the string to a bytes vector ([u8]) and this finally into a str object as this defines the used chars() function. The for loop finally converts the str into a Base integer. Can you see what it does - does the initial string really get represented in the u8? Do 8 bp really fit into this u8? And should that not throw an error?

```{bash,  error=TRUE}
cd sequences
cargo build -r
target/release/sequences
```


As said - this is not scope of this course, but I assume it will become interesting for you later on.
